### ISSUE TITLE
Any chance to port this demo to Ionic 2?

### ISSUE THREAD

**Issue by lobo-tuerto** [brakmic/Angular2_VR_Starter#2]
Now that Ionic 2 is at rc0 and Angular 2 final is out, it looks like a good time to play with this on a mobile device! :)

I tried including the minified script for **A-Frame** in the `index.html` and didn't get very far:

```
Uncaught TypeError: Cannot assign to read only property 'detachedCallback' of object '#<a-node>'
```

I'm just getting into Angular 2, Ionic 2 & Typescript so I don't have yet the skills to do it myself right now, but I'll keep trying.

If you can help that'd be great!

**Comment by brakmic** [comment]
Hi,

I suppose you've encountered problems with Shadow-DOM (part of the so-called "WebComponents" Suite of W3C-Standards).

Here's a thread from AFrame-Github where people discuss similar problems: https://github.com/aframevr/aframe/issues/1492

I think you should join them there and also check their weekly newsletter. Maybe someone has already ported A-Frame to Ionic (Mobile).

Regards,

**Comment by lobo-tuerto** [comment]
Thank you for the prompt answer and the suggestions. I already have it running in Ionic 2.

It was a matter of moving the `<script>` tag that imports it from the `<body>` to the `<head>`.

**Comment by amity203** [comment]
@lobo-tuerto  can you help me in getting aframe running in Ionic 2, i am trying but aframe code is not showing anything in chrome

**Comment by brakmic** [comment]
Sorry, but I'm not using Ionic.

**Comment by lobo-tuerto** [comment]
@amity203 Sure, let me setup a new project and upload to my repos this weekend. Follow me, so you get notified when it gets done.

**Comment by amity203** [comment]
@lobo-tuerto awesome, followed you

**Comment by lobo-tuerto** [comment]
@amity203 here it is: https://github.com/lobo-tuerto/a-frame-ionic2-hello-world
