### ISSUE TITLE
How to dynamically add entities

### ISSUE THREAD

**Issue by sebi-b** [brakmic/Angular2_VR_Starter#3]
Hey there!

Is it possible to add entititys dynamically to the scene? So for example if you click
a button in vr it creates another entity (not from the pool).

Thanks!

**Comment by brakmic** [comment]
Didn't understand your question. Maybe the docs from a-frame can provide further help.

https://aframe.io/docs/0.4.0/core/component.html

**Comment by sebi-b** [comment]
Hey Again,

Thanks for your quick reply!

My question is: How can I achieve this: 
https://aframe.io/docs/0.4.0/guides/using-javascript-and-dom-apis.html#adding-an-entity-with-appendchild

with your angular2 solution?

Because in Angular 2 the component doesnt rerender, so if i append something I just see the nodes as text and not as elements...

thanks again,

Sebi

**Comment by brakmic** [comment]
Dealing with Angular (or any other framework) implies knowing about their internals. I don't know how much you know about Angular but you should know that Angular will not re-render anything if you change any parts of the DOM _outside_ of it (for example, by using jQuery or document.* methods to manipulate some DIVs etc.).

I think your question touches broader concepts so the best thing you can do is to read about Angular's internals and how it handles DOM changes (Renderer, ViewChilds, Life-Cycle methods etc.) before you try anything more complex in this area.

https://angular.io/docs/js/latest/tutorial/

Have fun!
