### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by aammfe** [brakmic/Angular2_VR_Starter#4]
Hi!
i just clone this repo , and facing this error.

TSLint error:: Initialization error (tslint). Cannot find module 'E:\Angular\Angular-VR-Starter\node_modules\tslint'

i m new to angular and A-Frame , Kindly can u guide me what wrong with this...?

**Comment by brakmic** [comment]
Install tslint globally: 

```
npm i -g tslint
```

Regards,

**Comment by aammfe** [comment]
As i told u before i m new to Angular.
is there any One stop solution for me..?

just install that , and every thing start working fine ?

![image](https://cloud.githubusercontent.com/assets/11896817/26217921/9b5f464a-3c22-11e7-9c18-7bf27e2ede90.png)

**Comment by brakmic** [comment]
There's no such thing like "autoinstall" when dealing with complexities of Angular, A-Frame and WebPack together. This project is not for node/angular-beginners. 

In the above case you'll also need a proper (global) webpack installation. However, I'm not providing angular/node support here. You'll have to consult their docs first.

This installs webpack globally, but again: this project is not for beginners.
```
npm i -g webpack  
```

**Comment by aammfe** [comment]
Thanx 👍
