### ISSUE TITLE
protractor conf with Aframe

### ISSUE THREAD

**Issue by remkoboschker** [brakmic/Angular2_VR_Starter#7]
Why do you require the zone, after disabling the protractor synchronisation? I think it is to prevent e2e test from timing out. But could you please clarify?

```
onPrepare: function() {
        browser.ignoreSynchronization = true;
        require(helpers.root('node_modules/zone.js/dist/zone-node'));
    },
```

**Comment by brakmic** [comment]
I do not use protractor or any testing in this project. It's only a demo for an [article of mine](http://blog.brakmic.com/webvr-with-a-frame-angular/). The webpack/testing scripts are from [a project](https://github.com/AngularClass/angular-starter) I've used to build up the basis for the (more special) angular 2.x vr app. Maybe they can give you more info regarding protractor sync.

Regards,
